"""Rebuild src/components/icons/glyphPaths.ts from the glyph sources.

    pip install -r tools/glyphs/requirements.txt
    python3 tools/glyphs/export.py
"""
import os, sys, json, subprocess
HERE=os.path.dirname(os.path.abspath(__file__))
ROOT=os.path.abspath(os.path.join(HERE,"..",".."))
subprocess.run([sys.executable, os.path.join(HERE,"vfinal.py")], check=True, cwd=HERE)
V=json.load(open(os.path.join(HERE,"vfinal.json")))
bad=[k for k,v in V.items() if v["topo0"]!=v["topo1"] or v["dev"]>0.03]
if bad: sys.exit(f"audit failed for: {bad}")
lines=["/**",
" * Path data for the Good Will Grow glyph set. Generated by",
" * tools/glyphs/export.py — edit the generator, not this file.",
" *",
" * Every glyph is one path on a 24-unit grid, filled even-odd: cut-outs are",
" * real holes, so a glyph works on any surface without a second colour. The",
" * shapes follow rules measured off the reference sheet: pillow squircles",
" * (superellipse n=3.2) 20.8 across, circles 22 across, cut lines 2.05 wide,",
" * handles 2.1, badges r4.74 in a 1.91 ring, and every outer corner rounded",
" * to at least 0.4 (tips to 0.7) so nothing ends in a point.",
" */",
"export const glyphPaths = {"]
for n in sorted(V): lines.append(f'  {n}: "{V[n]["d"]}",')
lines+=["} as const;","","export type GlyphName = keyof typeof glyphPaths;",""]
out=os.path.join(ROOT,"src","components","icons","glyphPaths.ts")
open(out,"w").write("\n".join(lines)); print("wrote",out,len(V),"glyphs")
