import React from "react";
import { View } from "react-native";
import {
  BellGlyph,
  BellOffGlyph,
  BookmarkGlyph,
  CartGlyph,
  ChevronGlyph,
  CloseGlyph,
  CommentGlyph,
  ComposeGlyph,
  CrownGlyph,
  FolderGlyph,
  GiftGlyph,
  HeartGlyph,
  HomeGlyph,
  InfoGlyph,
  MemberGlyph,
  MenuGlyph,
  MoreGlyph,
  OrderGlyph,
  PhotoPostGlyph,
  PinGlyph,
  PlusGlyph,
  PosGlyph,
  PencilGlyph,
  PostAddGlyph,
  ProfileGlyph,
  SearchGlyph,
  SendGlyph,
  UserOffGlyph,
  UsersGlyph,
  VerifiedGlyph,
  StackGlyph,
  ActivityGlyph,
  AlertCircleGlyph,
  AlertTriangleGlyph,
  AtSignGlyph,
  BikeGlyph,
  BuildingGlyph,
  CalendarGlyph,
  CameraGlyph,
  CheckCircleGlyph,
  CheckGlyph,
  ChefHatGlyph,
  ClockGlyph,
  CloseCircleGlyph,
  CoffeeGlyph,
  CoinsGlyph,
  CopyGlyph,
  DownloadGlyph,
  HandCoinsGlyph,
  LockGlyph,
  MailGlyph,
  MinusGlyph,
  QrGlyph,
  ReceiptGlyph,
  RefreshGlyph,
  ScooterGlyph,
  ShareGlyph,
  SlidersGlyph,
  SparklesGlyph,
  StoreGlyph,
  TicketGlyph,
  TicketPercentGlyph,
  TrashGlyph,
  TrendDownGlyph,
  TrendUpGlyph,
  UserPlusGlyph,
  ArmchairGlyph,
  BanGlyph,
  CakeGlyph,
  ColdCupGlyph,
  CookieGlyph,
  DrumstickGlyph,
  EyeGlyph,
  FootprintsGlyph,
  GlobeGlyph,
  HashGlyph,
  HourglassGlyph,
  ImagePlusGlyph,
  ImagesGlyph,
  InfinityGlyph,
  MonitorGlyph,
  PauseGlyph,
  PhoneGlyph,
  SettingsGlyph,
  SoupGlyph,
  StarGlyph,
  TicketCheckGlyph,
  UserCheckGlyph,
  type GlyphProps,
} from "../GwgIcons";
import { ink } from "../../theme/colors";

/**
 * The app's icons, by name.
 *
 * These are drawn for this app rather than taken from the platform sets.
 * SF Symbols and Material Symbols are what every other app on the phone
 * already wears, and they differ between iOS and Android, so a screen built
 * from them has neither a face of its own nor one shape across platforms.
 * Drawing them keeps both.
 */
const glyphs = {
  home: HomeGlyph,
  order: OrderGlyph,
  member: MemberGlyph,
  profile: ProfileGlyph,
  compose: ComposeGlyph,
  pencil: PencilGlyph,
  cart: CartGlyph,
  menu: MenuGlyph,
  more: MoreGlyph,
  search: SearchGlyph,
  bookmark: BookmarkGlyph,
  bell: BellGlyph,
  heart: HeartGlyph,
  comment: CommentGlyph,
  gift: GiftGlyph,
  close: CloseGlyph,
  chevronRight: ChevronGlyph,
  pin: PinGlyph,
  stack: StackGlyph,
  photoPost: PhotoPostGlyph,
  verified: VerifiedGlyph,
  bellOff: BellOffGlyph,
  crown: CrownGlyph,
  info: InfoGlyph,
  plus: PlusGlyph,
  folder: FolderGlyph,
  users: UsersGlyph,
  userOff: UserOffGlyph,
  send: SendGlyph,
  postAdd: PostAddGlyph,
  pos: PosGlyph,
  activity: ActivityGlyph,
  atSign: AtSignGlyph,
  scooter: ScooterGlyph,
  bike: BikeGlyph,
  store: StoreGlyph,
  building: BuildingGlyph,
  calendar: CalendarGlyph,
  clock: ClockGlyph,
  camera: CameraGlyph,
  coffee: CoffeeGlyph,
  chefHat: ChefHatGlyph,
  coins: CoinsGlyph,
  handCoins: HandCoinsGlyph,
  copy: CopyGlyph,
  download: DownloadGlyph,
  share: ShareGlyph,
  lock: LockGlyph,
  mail: MailGlyph,
  minus: MinusGlyph,
  check: CheckGlyph,
  checkCircle: CheckCircleGlyph,
  closeCircle: CloseCircleGlyph,
  alertCircle: AlertCircleGlyph,
  alertTriangle: AlertTriangleGlyph,
  qr: QrGlyph,
  receipt: ReceiptGlyph,
  ticket: TicketGlyph,
  ticketPercent: TicketPercentGlyph,
  trash: TrashGlyph,
  trendUp: TrendUpGlyph,
  trendDown: TrendDownGlyph,
  refresh: RefreshGlyph,
  sliders: SlidersGlyph,
  sparkles: SparklesGlyph,
  userPlus: UserPlusGlyph,
  star: StarGlyph,
  ban: BanGlyph,
  settings: SettingsGlyph,
  eye: EyeGlyph,
  globe: GlobeGlyph,
  userCheck: UserCheckGlyph,
  ticketCheck: TicketCheckGlyph,
  imagePlus: ImagePlusGlyph,
  images: ImagesGlyph,
  hourglass: HourglassGlyph,
  pause: PauseGlyph,
  infinity: InfinityGlyph,
  monitor: MonitorGlyph,
  phone: PhoneGlyph,
  hash: HashGlyph,
  armchair: ArmchairGlyph,
  footprints: FootprintsGlyph,
  coldCup: ColdCupGlyph,
  drumstick: DrumstickGlyph,
  cake: CakeGlyph,
  soup: SoupGlyph,
  cookie: CookieGlyph,
} satisfies Record<string, React.ComponentType<GlyphProps>>;

export type AppIconName = keyof typeof glyphs;

interface AppIconProps {
  name: AppIconName;
  size?: number;
  color?: string;
  /** Fills the glyph; the silhouette stays the same either way. */
  emphasis?: boolean;
  /**
   * Quarter turns clockwise. The chevron is drawn once and turned, rather
   * than kept as four near-identical paths that can drift apart.
   */
  rotate?: 0 | 90 | 180 | 270;
}

export function AppIcon({
  name,
  size = 24,
  color = ink[500],
  emphasis,
  rotate = 0,
}: AppIconProps) {
  const Glyph = glyphs[name];
  const glyph = <Glyph size={size} color={color} active={emphasis} />;
  if (rotate === 0) return glyph;
  return <View style={{ transform: [{ rotate: `${rotate}deg` }] }}>{glyph}</View>;
}
